name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.0'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build ./...

    - name: Clear Module Cache
      run: go clean --modcache

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v5
      with:
        version: v1.57

    - name: Run tests
      run: make check